export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';
export const GET_TASK_LISTS_REQUEST = 'GET_TASK_LIST_REQUEST';
export const GET_TASK_LISTS_SUCCESS = 'GET_TASK_LIST_SUCCESS';
export const GET_TASK_LISTS_FAILURE = 'GET_TASK_LIST_FAILURE';